markdown: kramdown
kramdown:
    math_engine: katex
    katex:
        display_mode: true
        delimiters:
            - {left: "$$", right: "$$", display: true}
            - {left: "$", right: "$", display: true}